spring:
  profiles:
    active: ${PROFILE}

    application:
      name: bioautoml-api

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true

server:
  servlet:
    context-path: /api

  port: ${APPLICATION_PORT}

application:
  rabbit:
    queues:
      processes:
        init: baml.processes.init
        status: baml.processes.status
        results: baml.processes.results
        errors: baml.processes.errors
        email: baml.processes.results.send-email

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  aws:
    secret: ${AWS_SECRET}
    access: ${AWS_ACCESS}

    s3:
      bucket:
        name: ${AWS_S3_BUCKET_NAME}

  output:
    init:
      path: ${OUTPUT_INIT_PATH}
    end:
      path: ${OUTPUT_END_PATH}

  config:
    processes:
      amount: ${NUMBER_OF_CONCURRENT_PROCESSES}

  sendgrid:
    apikey: ${SENDGRID_API_KEY}
    from:
      email: ${SENDGRID_FROM_EMAIL}
---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bioautoml-api
    username: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

spring:
  profiles: prd
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  rabbitmq:
    addresses: ${RABBITMQ_ADDRESS}
