spring:
  profiles:
    active: ${PROFILE}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true

server:
  servlet:
    context-path: /api

  port: ${APPLICATION_PORT}

application:
  rabbit:
    queues:
      process:
        dna-rna: baml.processes.dna-rna
        wnm-dna-rna: baml.processes.wnm-dna-rna
        protein: baml.processes.protein
        binary-problems: baml.processes.binary-problems
        multiclass-problems: baml.processes.multiclass-problems

        parameters:
          afem: baml.processes.parameters.afem
          metalearning: baml.processes.parameters.metalearning

        status: baml.processes.status

        files: baml.processes.files

        results: baml.processes.results

      results:
        generate: baml.results.create-results

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  aws:
    secret: ${AWS_SECRET}
    access: ${AWS_ACCESS}

    s3:
      bucket:
        name: ${AWS_S3_BUCKET_NAME}

  output:
    init:
      path: ${OUTPUT_INIT_PATH}
    end:
      path: ${OUTPUT_END_PATH}
---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bioautoml
    username: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

spring:
  profiles: prd
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  rabbitmq:
    vhost: ${RABBIT_VHOST}
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}