spring:
  profiles:
    active: ${PROFILE}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true

server:
  servlet:
    context-path: /api

  port: 8080

application:
  rabbit:
    queues:
      process:
        dna-rna: dna-rna
        wnm-dna-rna: wnm-dna-rna
        protein: protein
        binary-problems: binary-problems
        multiclass-problems: multiclass-problems

      results:
        generate: create-results
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  aws:
    secret: ${AWS_SECRET}
    access: ${AWS_ACCESS}

    s3:
      bucket:
        name: ${AWS_S3_BUCKET_NAME}

  output:
    init:
      path: ${OUTPUT_INIT_PATH}
    end:
      path: ${OUTPUT_END_PATH}
---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bioautoml
    username: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

spring:
  profiles: prd
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}