name: Build Application and Deploy Image

on:
  push:
    branches: [ "main" ]

jobs:

  build-application:
    name: Build Application and Deploy Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK    
      uses: actions/setup-java@v1      
      with:        
       java-version: 1.11
       
    - name: Build with Maven      
      run: mvn clean install -DskipTests
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: bioautoml/api:latest, bioautoml/api:${{ github.run_number }}
        
  deploy:
    name: Deploy to GCP
    needs: build-application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: GCP Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
        
    - name: Deploy to GCP
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        image: 'docker.io/bioautoml/api:latest'
        secrets: 
          PROFILE=${{ secrets.APP_PROFILE }},
          MAX_FILE_SIZE=${{ secrets.APP_MAX_FILE_SIZE }},
          MAX_REQUEST_SIZE=${{ secrets.APP_MAX_REQUEST_SIZE }},
          JWT_SECRET=${{ secrets.APP_JWT_SECRET }},
          JWT_EXPIRATION=${{ secrets.APP_JWT_EXPIRATION }},
          AWS_SECRET=${{ secrets.APP_AWS_SECRET }},
          AWS_ACCESS=${{ secrets.APP_AWS_ACCESS }},
          AWS_S3_BUCKET_NAME=${{ secrets.APP_AWS_S3_BUCKET_NAME }},
          OUTPUT_INIT_PATH=${{ secrets.APP_OUTPUT_INIT_PATH }},
          OUTPUT_END_PATH=${{ secrets.APP_OUTPUT_END_PATH }},
          APPLICATION_PORT=${{ secrets.APP_APPLICATION_PORT }},
          POSTGRES_URL=${{ secrets.APP_POSTGRES_URL }},
          POSTGRES_USERNAME=${{ secrets.APP_POSTGRES_USERNAME }},
          POSTGRES_PASSWORD=${{ secrets.APP_POSTGRES_PASSWORD }},
          RABBITMQ_ADDRESS=${{ secrets.APP_RABBITMQ_ADDRESS }}
          
        
        
