name: Build and Deploy APP

on:
  push:
    branches: [ "main" ]

jobs:

  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK    
      uses: actions/setup-java@v1      
      with:        
       java-version: 1.11
       
    - name: Build with Maven      
      run: mvn clean install -DskipTests

  build-push-docker-image:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [build-application]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
          -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .

      - name: Publish Docker image
        run: docker push $REPO
        
  deploy:
    name: Deploy to VPS
    needs:
      - build-application
      - build-push-docker-image
    runs-on: ubuntu-latest
    env:
      APP_PORT: ${{ secrets.APP_APPLICATION_PORT }}
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: Pull, Build and Deploy Docker Image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker image pull ${{ secrets.DOCKER_REPO }}:latest
            docker container run --restart unless-stopped -d -p $APP_PORT:$APP_PORT \
            -e PROFILE=${{ secrets.APP_PROFILE }} \
            -e MAX_FILE_SIZE=${{ secrets.APP_MAX_FILE_SIZE }} \
            -e MAX_REQUEST_SIZE=${{ secrets.APP_MAX_REQUEST_SIZE }} \
            -e JWT_SECRET=${{ secrets.APP_JWT_SECRET }} \
            -e JWT_EXPIRATION=${{ secrets.APP_JWT_EXPIRATION }} \ 
            -e AWS_SECRET=${{ secrets.APP_AWS_SECRET }} \
            -e AWS_ACCESS=${{ secrets.APP_AWS_ACCESS }} \
            -e AWS_S3_BUCKET_NAME=${{ secrets.APP_AWS_S3_BUCKET_NAME }} \
            -e OUTPUT_INIT_PATH=${{ secrets.APP_OUTPUT_INIT_PATH }} \
            -e OUTPUT_END_PATH=${{ secrets.APP_OUTPUT_END_PATH }} \
            -e APPLICATION_PORT=${{ secrets.APP_APPLICATION_PORT }} \
            -e POSTGRES_URL=${{ secrets.APP_POSTGRES_URL }} \
            -e POSTGRES_USERNAME=${{ secrets.APP_POSTGRES_USERNAME }} \
            -e POSTGRES_PASSWORD=${{ secrets.APP_POSTGRES_PASSWORD }} \
            -e RABBITMQ_ADDRESS=${{ secrets.APP_RABBITMQ_ADDRESS }} \
            -e NUMBER_OF_CONCURRENT_PROCESSES=${{ secrets.APP_NUMBER_OF_CONCURRENT_PROCESSES }} \
            $REPO:latest
            
            

