name: Build and Deploy APP

on:
  push:
    branches: [ "main" ]

jobs:

  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK    
      uses: actions/setup-java@v1      
      with:        
       java-version: 1.11
       
    - name: Build with Maven      
      run: mvn clean install -DskipTests

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: bioautoml/api:latest, bioautoml/api:${{ github.run_number }}
        
  deploy:
    name: Deploy to VPS
    needs:
      - build-application
    runs-on: ubuntu-latest

    steps:
      - name: Pull, Build and Deploy Docker Image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker image pull bioautoml/api:latest
            docker container stop bioautoml-api
            docker container rm bioautoml-api
            docker container run --name bioautoml-api --restart unless-stopped -d -p ${{ secrets.APP_APPLICATION_PORT }}:${{ secrets.APP_APPLICATION_PORT }} -e PROFILE=${{ secrets.APP_PROFILE }} -e MAX_FILE_SIZE=${{ secrets.APP_MAX_FILE_SIZE }} -e MAX_REQUEST_SIZE=${{ secrets.APP_MAX_REQUEST_SIZE }} -e JWT_SECRET=${{ secrets.APP_JWT_SECRET }} -e JWT_EXPIRATION=${{ secrets.APP_JWT_EXPIRATION }} -e AWS_SECRET=${{ secrets.APP_AWS_SECRET }} -e AWS_ACCESS=${{ secrets.APP_AWS_ACCESS }} -e AWS_S3_BUCKET_NAME=${{ secrets.APP_AWS_S3_BUCKET_NAME }} -e OUTPUT_INIT_PATH=${{ secrets.APP_OUTPUT_INIT_PATH }} -e OUTPUT_END_PATH=${{ secrets.APP_OUTPUT_END_PATH }} -e APPLICATION_PORT=${{ secrets.APP_APPLICATION_PORT }} -e POSTGRES_URL=${{ secrets.APP_POSTGRES_URL }} -e POSTGRES_USERNAME=${{ secrets.APP_POSTGRES_USERNAME }} -e POSTGRES_PASSWORD=${{ secrets.APP_POSTGRES_PASSWORD }} -e RABBITMQ_ADDRESS=${{ secrets.APP_RABBITMQ_ADDRESS }} -e NUMBER_OF_CONCURRENT_PROCESSES=${{ secrets.APP_NUMBER_OF_CONCURRENT_PROCESSES }} bioautoml/api:latest